### ISSUE TITLE
Buttons overlapped when installing extensions 

### ISSUE THREAD

**Issue by javigomez** [joomla-projects/joomla-browser#102]
We need to improve the scrollTo, to avoid this situations:

Button is overlapped and can't be clicked

![capture 2016-02-01 at 12 57 46](https://cloud.githubusercontent.com/assets/1375475/13393823/201236ce-dee4-11e5-8f45-0611215a5884.png)

See https://github.com/Codeception/Codeception/issues/2840

**Comment by puneet0191** [comment]
@javigomez Should we include the function call inside extension Installation function? Right now we are calling it separately from the cest files.

**Comment by puneet0191** [comment]
resolved
