### ISSUE TITLE
Add support for different languages

### ISSUE THREAD

**Issue by shanginn** [joomla-projects/joomla-browser#118]
This is really great component, big thanks!
But right now it only support English and I want to test my extension in different language(Russian).
There is no way I can do it. I can install and change default language, but after that nothing is working, because many methods rely on strings(in English, ofc), like 'Log out' or 'Log in'.
Maybe the best way to solve it - load Joomla Application into JoomlaBrowser class and use JText class inside. What do you think?

**Comment by yvesh** [comment]
Hi @shanginn, we thought on multiple approaches here and still try to figure out the best one for locators. Whenever there are easy CSS selectors (id, class etc.) we try to use them, but text strings have a big advantage in readability.

**Comment by puneet0191** [comment]
@shanginn Thanks for sharing this, I agree with the issue you have raised and I think it is a valid one. @yvesh  May be we should think of a way where we detect the default language and use this to have different steps of execution, in case of English our Default steps execute and In case of Default language not equal to English, we replace all the strings with Xpaths, CSS, Id locators. What do you think?

**Comment by shanginn** [comment]
I wrote some code to import default language, I just don't know where to put it.
In this code we initialise Joomla application after install and load default languge.

``` php
<?php
define('_JEXEC', 1);
define('JPATH_BASE', "/var/www/path_to_joomla");

require_once JPATH_BASE . '/includes/defines.php';
require_once JPATH_BASE . '/includes/framework.php';

JFactory::getApplication('site')->initialise();

$lang_params = JComponentHelper::getParams('com_languages');
$admin_lang = $lang_params->get('administrator');
$front_lang = $lang_params->get('site');

JFactory::$language = JLanguage::getInstance($admin_lang, 0);
```

And then we can use JText with standard Joomla lang constants, like this:

``` php
echo JText::_('JLOGIN');
```

And we can include lang files from component and use them in multilanguage tests.

**Comment by yvesh** [comment]
For including language files of the component we would need a new parameter in the acceptance.suite.yml. A better and more general approach would be we write a codeception extension for Joomla! which does the language loading etc. This is definitely something i would like to look into.

But from a overall-view imo it would be better to abandon language locators at all (when we find an appropriate replacement, which keeps readability).

**Comment by shanginn** [comment]
@yvesh it's not only question of "an appropriate replacement" - language is a must-have feature. What if my extension is multilang and I want to test it in each lang? or, for example, each component have own messages for each action and how I can test this actions without translating each of COM_FOO_EXAMPLE_ACTION_ERROR_ETC into some language? If you know what I mean :)
And there is no need for .yml parametr, we can grab user default language, like I said above

**Comment by yvesh** [comment]
You can grab the default language of an installed Joomla, yes. But not the extension (e.g. com_weblinks) you test :-)

**Comment by shanginn** [comment]
There is no "default extension language" :)
But we only need default language of an installed Joomla and `JText::_()` function for tests. If in your tests you need to check for `COM_FOO_OK` message, all you need to do is look for `JText::_('COM_FOO_OK')`. And if there is translation to enabled Joomla language you'll see some "Component Foo ok message" in the test part and the same in the Joomla site, but if there is no translation, you will see `COM_FOO_OK`, again, both in the tests and in the site. Does this make sense? :)

**Comment by puneet0191** [comment]
This can now be used with the help of Locators option in Yaml, and try to change the locators and text to custom language. Closing the issue
