### ISSUE TITLE
Remove redundant word #14607

### ISSUE THREAD

**Issue by astridx** [joomla-projects/joomla-browser#133]
Because of https://github.com/joomla/joomla-cms/pull/14607/files we have to make much changes in Joomla-browser.
Only one example (where we have to delete the word successfully): https://github.com/joomla-projects/joomla-browser/blob/develop/src/JoomlaBrowser.php#L315

**Comment by puneet0191** [comment]
This will be part of 3.8? Isn't it @astridx @rdeutz

**Comment by astridx** [comment]
Yes, it this changes are in the 3.8 milestone. But as we use the current staging for developing weblinks there are already now failures.

**Comment by puneet0191** [comment]
I am going to close this issue, it has been addressed. Thank you @astridx
