### ISSUE TITLE
Not J4 compatible

### ISSUE THREAD

**Issue by stell** [joomla-projects/joomla-browser#242]
Is this still in use? Many of the functions (createMenuItem, selectOptionInRadioField, enablePlugin, selectOptionInChosenById) are not J4 compatible or obsolete.

**Comment by Hackwar** [comment]
For 3.x yes. For 4.x we are switching over to cypress and we are working on a replacement with joomla-projects/joomla-cypress this will not be adapted further to 4.x

**Comment by stell** [comment]
Yes, I saw that you are working on cypress tests. Looks good.
We'll stick with codeception for now and adapt the browser for J4. Maybe someone can use it.
Is or has this been updated for cypress? 
https://docs.joomla.org/Testing_Joomla_Extensions_with_Codeception

**Comment by HLeithner** [comment]
@stell if you make pull requests against the joomla-browser we will merge them.

**Comment by HLeithner** [comment]
about the documentation @rdeutz has started a pr for the new programmers documentation system and how to use cypress, but since it's not ready yet it's not merged.
https://github.com/joomla/Manual/pull/12

**Comment by svenbluege** [comment]
@stell I'm pretty bad with MRs :(, but I use the Codecept-test für J3&J4. The necessary changes for J4 I did here: https://github.com/svenbluege/joomla-browser/tree/J4.0

**Comment by stell** [comment]
@svenbluege Looks like `enablePlugin` and `createMenuItem` will not work in J4. But we'll look into it if necessary. Thanks.

**Comment by svenbluege** [comment]
@stell true, have my own function to create menu items + do some configurations. But I use enablePlugin and this works (for me ;)
