### ISSUE TITLE
Find a reliable method to deal with Input field drop down select in Joomla!

### ISSUE THREAD

**Issue by puneet0191** [joomla-projects/joomla-browser#68]
Need a method in Joomla! browser to interact with select drop down with Input Field

![image](https://cloud.githubusercontent.com/assets/3048593/10394538/8d3fb1a8-6eb5-11e5-8f26-2a1abc072d0b.png)

**Comment by javigomez** [comment]
This function should update the current: https://github.com/joomla-projects/joomla-browser/blob/develop/src/JoomlaBrowser.php#L412-L428 allowing Multiselect like when selecting tags in Articles

![capture 2015-10-04 at 15 48 38](https://cloud.githubusercontent.com/assets/1375475/10821808/969c39f2-7e54-11e5-8394-9744963b78b2.png)
