### ISSUE TITLE
Can't install joomla on windows

### ISSUE THREAD

**Issue by compojoom** [joomla-projects/joomla-browser#70]
The system test fails to install joomla on my Windows machine. The test fails to find the next button on the page with the language select.

I see that in the test we have this
```
 // Select a random language to force reloading of the lang strings after selecting English
$I->selectOptionInChosen('#jform_language', 'Danish (DK)');
$I->selectOptionInChosen('#jform_language', 'English (United Kingdom)');
```

In my case I end up with danish, instead of english. Tried with waiting 2 sec between the selection, but this didn't help either. The only way to go around this is to just select english. 

I'm also not sure that I understand the logic of the comment? Force reloading of the lang strings? The default language is english? Why do we need to reload it?

**Comment by puneet0191** [comment]
@compojoom I think this was added to verify if the strings were getting reloaded to the language selected(in this case from Danish to English again), Ideally a waitForText between the two selects should have solved the problem try increasing the time to 10 sec.

**Comment by javigomez** [comment]
see details at https://github.com/joomla-projects/joomla-browser/pull/59

**Comment by javigomez** [comment]
@compojoom if you have an alternative using JS would be okay.

Needs to be tested with a Firefox browser that has default language other than English.

**Comment by compojoom** [comment]
https://github.com/joomla-projects/joomla-browser/pull/72 - this one should fix it.

**Comment by yvesh** [comment]
As this is merged we can now close this.

**Comment by Kubik-Rubik** [comment]
Thanks guys!
