### ISSUE TITLE
Toolbar commands fail at 480px resolution

### ISSUE THREAD

**Issue by therunnergit** [joomla-projects/joomla-browser#80]
At 480px resolution the toolbar buttons are hidden and only one "Toolbar" button is visibile. To see all buttons, you have to click on "Toolbar" first.

So, at this resolution, any step that requires a click on a toolbar button will fail.

**Comment by Kubik-Rubik** [comment]
Thank you for testing it @therunnergit.

What do you think, do we need separated tests for the small resolution? Or we could just check whether the toolbar is available or not in the same test?

**Comment by puneet0191** [comment]
I am on it, we can just check if the resolution is different and perform different action in Joomla! browser to handle the toolbar command.

**Comment by Kubik-Rubik** [comment]
@puneet0191 :+1:

**Comment by puneet0191** [comment]
I have done a PR to handle this. 
https://github.com/joomla-projects/joomla-browser/pull/82

**Comment by puneet0191** [comment]
Please test the PR and close the issue.
